### ISSUE TITLE
About really free storage

### ISSUE THREAD

**Issue by ppKrauss** [openimagerynetwork/oin-register#19]
Hi, good initiative, congratulations! 

This issue is  only a comment and little suggestion to text enhancement. Perhaps  a better text, at README's *"Create an object store"*, better tham *"This can be Amazon S3, Microsoft Azure, or Google Cloud Storage"*, that are all commertial: even in [freemium business model](https://en.wikipedia.org/wiki/Freemium) context,  the hosting-company generates dependence, so later [high transaction cost](https://en.wikipedia.org/wiki/Transaction_cost) to move away... See recent problems with Google changes, a big problem with geocoding, map-view, etc... 

I am supposing that *oin-register* is also an initiative of [digital preservation](https://en.wikipedia.org/wiki/Digital_preservation).

**Suggestion**: to  cite also non-commertial or less-cost-to-change alternatives,

* Git Large File Storage (LFS), see https://git-lfs.github.com/
*  [IPFS](https://en.wikipedia.org/wiki/InterPlanetary_File_System)  (and [Filecoin business model](https://en.wikipedia.org/wiki/Filecoin) for long-term digital preservation)
* ... 

------

PS: for all HTTP-dependent solutions, the README can show some clues or instructions about "image internet address". Even here with Github we can avoid company-dependence and **cost to move away**, by the use of a stable (ideial to be collective) non-commertial domain. Example: [datasets.ok.org.br](http://datasets.ok.org.br) subdomain, and the git repositories (e.g. [state-codes](http://datasets.ok.org.br/state-codes)) are all Github, but we can move away to GitLab or any other at any moment, without cost.

**Comment by sethfitz** [comment]
Hi, thanks for writing in.

OIN's goals as a metadata specification have largely been subsumed into [STAC](https://github.com/radiantearth/stac-spec).

Organizations involved in storing + processing remotely-sensed data are often operating at the petabyte+ scale. Efficient access to partial images is also key, which is why we recommend object stores when making data available. In practice, any web server that supports HTTP Range requests (at a sufficiently-high volume; many municipal GIS data portals fall down under minor (by our standards) load) is sufficient.

Minio is an excellent, self-hosted alternative to S3 (with the same API), and there are others.

Git LFS, IPFS, and other peer-to-peer storage mechanisms are appealing, but they ultimately don't match OIN's goals.

**Comment by ppKrauss** [comment]
Thanks @mojodna.  Ok, make sense.  

------

NOTES

The Minio suggestion seems good, and I used it to check IPFS... Good news (!for me and you), see https://discuss.ipfs.io/t/large-files-long-term-storage/4447/2
