### ISSUE TITLE
Logo for Open Imagery Network

### ISSUE THREAD

**Issue by lossyrob** [openimagerynetwork/oin-register#7]
We need a logo for Open Imagery Network.

@designmatty has done these logo explorations:
![logo1](http://i.imgur.com/8O5Cdby.png)
![logo2](http://i.imgur.com/aMws4T6.png)
![logo3](http://i.imgur.com/GiCIXxS.png)

Does anyone have feedback or preferences?

**Comment by wonderchook** [comment]
I really like the dove one, it would look sweet on a t-shirt.

**Comment by lossyrob** [comment]
I agree, the dove is awesome. I like the idea of having the dove, and "open imagery network" under it. Perhaps once people get used to seeing the dove we can use the image on it's own sans text.

**Comment by wonderchook** [comment]
Yes a version with the text under it would be good.

**Comment by cholmes** [comment]
I like the dove, and agree some text to start would be good. Note Planet does use doves a lot and calls our satellites doves. But it won't be our main logo, so I think there's only minor overlap.

**Comment by lossyrob** [comment]
We've been calling it a dove, but in actuality it's an [Artic Tern](http://en.wikipedia.org/wiki/Arctic_tern). @designmatty had the idea to use the Arctic Tern because of it's migratory path, which essentially covers the whole world:

![arctic tern migration path](http://upload.wikimedia.org/wikipedia/commons/c/c7/Sterna_paradisaea_distr_mig.png)

He said he's going to do some iterations on that idea, so more soon.

**Comment by designmatty** [comment]
Hey everyone. Thought it was a good time for me to swing by and chime in a little bit. As @lossyrob mentioned, I thought it might be nice to have the bird act as a representation of global unity, which I thought the Arctic Tern could be due to its global migration pattern. 

I'll be pushing the idea further and will introduce a version with the word mark to see if this is the direction we want to go. Please feel free to chime in with more feedback everyone.

**Comment by smit1678** [comment]
nice work @designmatty @lossyrob. I dig the bird direction, but maybe a little lighter if that makes sense. 

> I'll be pushing the idea further and will introduce a version with the word mark to see if this is the direction we want to go.

Cool, was going to suggest this.

**Comment by ricardoduplos** [comment]
Hey @designmatty. Congrats on the logo design. I really like the use of the Artic Tern - for what it represents.

As for the companion text pointed out by @wonderchook, I would suggest the use of [Open Sans](https://www.google.com/fonts/specimen/Open+Sans) Bold, so we can keep some consistency among all OAM/OIN products. _Vide_ [OAM logo](https://github.com/hotosm/OpenAerialMap/issues/7).

**Comment by designmatty** [comment]
@ricardomestre Thanks for the suggestion. I actually love Open Sans so I'm all for its use here.

**Comment by designmatty** [comment]
Hey everyone, I did a some more work to the Tern bird logo. 

I introduced the word mark to the planet/bird combo. There's another version with a lighter blue. 

Variety is the spice of life so I put together an alternate version of the tern and wanted to see which everyone preferred. 

Cheers!

![oin-tern-logo](https://cloud.githubusercontent.com/assets/1928955/8007851/7a0bd046-0b6c-11e5-8702-6a43f4321e84.png)
![oin-tern-logo-lite-blue](https://cloud.githubusercontent.com/assets/1928955/8007857/7d63af3e-0b6c-11e5-9abc-3ac85922823d.png)
![oin-tern-logo-alt](https://cloud.githubusercontent.com/assets/1928955/8007861/7f9e5362-0b6c-11e5-81a9-fd8eb56380a4.png)

**Comment by designmatty** [comment]
I just got some awesome feedback and updated the logo. I like it a lot more now but I'll let you all decide.
![oin-tern-logo-lite-blue-v2](https://cloud.githubusercontent.com/assets/1928955/8009012/bd43afda-0b73-11e5-984b-e67f3c752fbc.png)

**Comment by lossyrob** [comment]
The latest image you posted is really great. I want to set that as the Github organization image to replace the default one. Are people good with that?

**Comment by cholmes** [comment]
+1

**Comment by wonderchook** [comment]
Love it!

**Comment by smit1678** [comment]
:+1:

**Comment by cgiovando** [comment]
@designmatty @lossyrob - do we have vector versions of the latest logo iteration? I'm planning to print a bunch of OAM and OIN stickers, and would be nice to shape it so that the text fits within or around the logo. Do you think we can wrap "Open Imagery Network" around the globe outline?

**Comment by designmatty** [comment]
Hey @cgiovando I completely forgot to upload the vector here. I also made an iteration on the logo with some more abstraction of the land masses on the earth. 
<img width="794" alt="oin-tern-logo" src="https://cloud.githubusercontent.com/assets/1928955/9660157/30b4b30c-5222-11e5-82c4-855af3c950bb.png">

I'm sorry but I don't have any time to work on wrapping the text around the globe (preparing to go on vacation). As for wrapping the the text around the globe, I personally wouldn't recommend it simply because text wrapping around a shape always turns out wonky.

I've put the the vectors up on my google drive open to the public https://drive.google.com/folderview?id=0B34sFvhrpo5CfkJxU1kwS2lzSnYweFNwOVAxVEVGNU42RWVxOW5QS3dfZFl6cEdLZnJGMXc&usp=sharing
